language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
env:
  ci: true
script:
  - npm run lint
  - npm run test:coverage:ci
  - npm run build
after_success:
  - npm run semantic-release
