name: CI
on: [push, pull_request]

jobs:
  build:
    name: Lint, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage:ci

      - name: Build
        run: npm run build

      - name: Semantic release
        run: npm run semantic-release
