name: CD
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Semantic release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
